name: Generate Mixed Version Testing Artifacts
on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - .github/workflows/secondary-umbrella.yaml
jobs:
  package-generic-unix:
    name: package-generic-unix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - erlang_major: "23"
          tag: v3.8.27
          patch: |
            diff --git a/WORKSPACE.bazel b/WORKSPACE.bazel
            index 62514c79af..5dc3169c75 100644
            --- a/WORKSPACE.bazel
            +++ b/WORKSPACE.bazel
            @@ -59,8 +59,8 @@ rules_pkg_dependencies()

             http_archive(
                 name = "bazel-erlang",
            -    sha256 = "f37c339711ce05b748688938ad9b1c00a78f0b2ef67d6baa734f5a34e33ad8a3",
            -    strip_prefix = "bazel-erlang-1.4.0",
            +    sha256 = "2ba878df673020ac714c050c0aaf3c66cac2f9cca0aa4259e3c74603c59e0cd0",
            +    strip_prefix = "rules_erlang-1.4.0",
                 urls = ["https://github.com/rabbitmq/bazel-erlang/archive/refs/tags/1.4.0.zip"],
             )

            diff --git a/rabbitmq.bzl b/rabbitmq.bzl
            index f0e7b7470d..f8e18aabb3 100644
            --- a/rabbitmq.bzl
            +++ b/rabbitmq.bzl
            @@ -25,6 +25,8 @@ _LAGER_EXTRA_SINKS = [
             ]

             RABBITMQ_ERLC_OPTS = DEFAULT_ERLC_OPTS + [
            +    "-DTEST=1",
            +    "+nowarn_export_all",
                 "+{parse_transform,lager_transform}",
                 "+{lager_extra_sinks,[" + ",".join(_LAGER_EXTRA_SINKS) + "]}",
             ]
        - erlang_major: "24"
          tag: v3.9.13
          patch: |
            diff --git a/rabbitmq.bzl b/rabbitmq.bzl
            index 852a156d33..e85da53960 100644
            --- a/rabbitmq.bzl
            +++ b/rabbitmq.bzl
            @@ -9,7 +9,10 @@ load("@bazel-erlang//:ct_sharded.bzl", "ct_suite", "ct_suite_variant")
             load("//:rabbitmq_home.bzl", "rabbitmq_home")
             load("//:rabbitmq_run.bzl", "rabbitmq_run")

            -RABBITMQ_ERLC_OPTS = DEFAULT_ERLC_OPTS
            +RABBITMQ_ERLC_OPTS = DEFAULT_ERLC_OPTS + [
            +    "-DTEST=1",
            +    "+nowarn_export_all",
            +]

             RABBITMQ_TEST_ERLC_OPTS = DEFAULT_TEST_ERLC_OPTS + [
                 "+nowarn_export_all",
        - erlang_major: "24"
          tag: v3.10.6
          patch: |
            diff --git a/rabbitmq.bzl b/rabbitmq.bzl
            index 85f9a2d790..08c2bc957e 100644
            --- a/rabbitmq.bzl
            +++ b/rabbitmq.bzl
            @@ -28,6 +28,8 @@ STARTS_BACKGROUND_BROKER_TAG = "starts-background-broker"
             MIXED_VERSION_CLUSTER_TAG = "mixed-version-cluster"

             RABBITMQ_ERLC_OPTS = DEFAULT_ERLC_OPTS + [
            +    "-DTEST=1",
            +    "+nowarn_export_all",
                 "-DINSTR_MOD=gm",
             ]
    timeout-minutes: 20
    steps:
    - name: Checkout Repository (Secondary Umbrella tag)
      uses: actions/checkout@v3
      with:
        ref: ${{ matrix.tag }}

    - name: Adjust Project-Wide erlc_opts
      run: |
        set -eux
        PATCH_FILE=secondary-umbrella.patch
        echo '${{ matrix.patch }}' > ${PATCH_FILE}
        cat ${PATCH_FILE}
        patch -p1 < ${PATCH_FILE}
        git diff

    - name: Mount Bazel Cache
      uses: actions/cache@v3.0.7
      with:
        path: "/home/runner/repo-cache/"
        key: repo-cache-secondary-umbrella

    - name: Configure Bazel
      run: |
        if [ -n "${{ secrets.BUILDBUDDY_API_KEY }}" ]; then
        cat << EOF >> user.bazelrc
          build:buildbuddy --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_API_KEY }}
        EOF
        fi
        cat << EOF >> user.bazelrc
          build:buildbuddy --build_metadata=ROLE=CI
          build:buildbuddy --build_metadata=VISIBILITY=PRIVATE
          build:buildbuddy --remote_instance_name=buildbuddy-io/buildbuddy/ci-secondary-umbrella
          build:buildbuddy --repository_cache=/home/runner/repo-cache/
          build:buildbuddy --color=yes
          build:buildbuddy --disk_cache=

          build:buildbuddy --remote_download_toplevel
        EOF

        bazelisk info release

    - name: Build
      run: |
        TAG=${{ matrix.tag }}
        VERSION=${TAG#v}
        sed -i"_orig" -E "/APP_VERSION/ s/3\.[0-9]+\.[0-9]+/${VERSION}/" rabbitmq.bzl
        bazelisk build :package-generic-unix \
          --config=rbe-${{ matrix.erlang_major }} \
          --verbose_failures

    - name: Rename the Artifact
      run: |
        OUTPUT_DIR=${{ github.workspace }}/output
        mkdir ${OUTPUT_DIR}
        cp \
          bazel-bin/package-generic-unix.tar.xz \
          ${OUTPUT_DIR}/package-generic-unix-for-mixed-version-testing-${{ matrix.tag }}.tar.xz

    - name: Upload the archive to S3
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --acl public-read --follow-symlinks
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: output
        DEST_DIR: secondary-umbrellas

    - name: Confirm public access
      run: |
        curl -LO https://rabbitmq-github-actions.s3.eu-west-1.amazonaws.com/secondary-umbrellas/package-generic-unix-for-mixed-version-testing-${{ matrix.tag }}.tar.xz
