name: Update rbe-erlang-platform
on:
  schedule:
  - cron: '0 3 * * *'
  workflow_dispatch:
jobs:
  update-rbe-images:
    name: Update rbe-erlang-platform
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: CHECKOUT REPOSITORY
      uses: actions/checkout@v3
      with:
        path: rabbitmq-server
    - name: CHECKOUT rbe-erlang-platform REPOSITORY
      uses: actions/checkout@v3
      with:
        path: rbe-erlang-platform
        repository: rabbitmq/rbe-erlang-platform
        ref: linux-rbe
    - name: DETERMINE LATEST COMMIT
      id: find-commit
      working-directory: rbe-erlang-platform
      run: |
        echo "::set-output name=SHA::$(git rev-parse HEAD)"
    - name: UPDATE rbe-erlang-platform COMMIT
      working-directory: rabbitmq-server
      run: |
        sudo npm install --global --silent @bazel/buildozer
        echo "$(cat WORKSPACE.bazel | npx buildozer 'set commit "${{ steps.find-commit.outputs.SHA }}"' -:rbe)" > WORKSPACE.bazel
        git diff
    - name: CREATE PULL REQUEST
      uses: peter-evans/create-pull-request@v4.0.4
      with:
        token: ${{ secrets.REPO_SCOPED_TOKEN }}
        committer: GitHub <noreply@github.com>
        author: GitHub <noreply@github.com>
        title: Adopt latest rabbitmq-server-buildenv:linux-rbe for RBE
        body: >
          Automated changes created by
          ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          using the [create-pull-request](https://github.com/peter-evans/create-pull-request)
          GitHub action

          Source workflow: `${{ github.action_path }}`
        path: rabbitmq-server
        commit-message: |
          Use latest rbe-erlang-platform/linux-rbe

          for remote build execution (RBE) with BuildBuddy
        labels: |
          backport-v3.11.x
          backport-v3.10.x
          backport-v3.9.x
          backport-v3.8.x
        branch: bump-rbe
        delete-branch: true
